/**
 * Nota 23: Nombre de la Institución o dependencia que emitió la exoneración
 */
enum INSTITUCION_EXONERACION {
  _01_MINISTERIO_DE_HACIENDA = '01',
  _02_MINISTERIO_RELACIONES_EXTERIORES_Y_CULTO = '02',
  _03_MINISTERIO_AGRICULTURA_Y_GANADERIA = '03',
  _04_MINISTERIO_ECONOMIA_INDUSTRIA_Y_COMERCIO = '04',
  _05_CRUZ_ROJA_COSTARRICENSE = '05',
  _06_BOMBEROS_DE_COSTA_RICA = '06',
  _07_ASOCIACION_OBRAS_DEL_ESPIRITU_SANTO = '07',
  _08_FEDERACION_CRUZADA_NACIONAL_PROTECCION_ANCIANO = '08',
  _09_EARTH = '09',
  _10_INCAE = '10',
  _11_JUNTA_DE_PROTECCION_SOCIAL = '11',
  _12_ARESEP = '12',
  _99_OTROS = '99'
}

export { INSTITUCION_EXONERACION };
