/**
 * Tipo de Comprobante Electronico
 */
enum TIPO_DOCUMENTO {
  _01_FACTURA_ELECTRONICA = '01',
  _02_NOTA_DEBITO_ELECTRONICA = '02',
  _03_NOTA_CREDITO_ELECTRONICA = '03',
  _04_TIQUETE_ELETRONICO = '04',
  _05_CONFIRMACION_ACEPTACION_COMPROBANTE_ELECTORNICO = '05',
  _06_CONFIRMACION_ACEPTACION_PARCIAL_COMPROBANTE_ELECTRONICO = '06',
  _07_CONFIRMACION_RECHAZO_COMPROBANTE_ELECTRONICO = '07',
  _08_FACTURA_ELETRONICA_COMPRA = '08',
  _09_FACTURA_ELETRONICA_EXPORTACION = '09',
  _10_RECIBO_ELETRONICO_PAGO = '10'
}

export { TIPO_DOCUMENTO };
