enum TIPO_DOCUMENTO_OTROS_CARGOS {
  _01_CONTRIBUCION_PARAFISCAL = '01',
  _02_TIMBRE_CRUZ_ROJA = '02',
  _03_TIMBRE_BOMBEROS = '03',
  _04_COBRO_DE_UN_TERCERO = '04',
  _05_COSTOS_DE_EXPORTACION = '05',
  _06_IMPUESTO_DE_SERVICIO_10 = '06',
  _07_TIMBRE_COLEGIOS_PROFESIONALES = '07',
  _08_DEPOSITOS_DE_GARANTIA = '08',
  _09_MULTAS_O_PENALIZACIONES = '09',
  _10_INTERESES_MORATORIOS = '10',
  _99_OTROS_CARGOS = '99'
}

export { TIPO_DOCUMENTO_OTROS_CARGOS };
