/**
 * Nota 20: Tipos de descuentos a utilizar en el campo "Código del Descuento"
 */
enum TIPO_DESCUENTO {
  _01_DESCUENTO_POR_REGALIA = '01',
  _02_DESCUENTO_POR_REGALIA_O_BONIFICACION_IVA_COBRADO_AL_CLIENTE = '02',
  _03_DESCUENTO_POR_BONIFICACION = '03',
  _04_DESCUENTO_POR_VOLUMEN = '04',
  _05_DESCUENTO_POR_TEMPORADA_ESTACIONAL = '05',
  _06_DESCUENTO_PROMOCIONAL = '06',
  _07_DESCUENTO_COMERCIAL = '07',
  _08_DESCUENTO_POR_FRECUENCIA = '08',
  _09_DESCUENTO_SOSTENIDO = '09',
  _99_OTROS_DESCUENTOS = '99'
}

export { TIPO_DESCUENTO };
